---
# Setup variables and facts.
- name: Include OS-specific vars
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - nginx

- name: Define nginx_user
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined
  tags:
    - nginx

- name: Ensure that Nginx user is exist
  user:
    name: "{{ nginx_user }}"
    system: yes
  tags:
    - nginx
